### ISSUE TITLE
Local knowledge-context throws error if the folder doesn't exists

### ISSUE THREAD

**Issue by kevin-denis-thales** [ThalesGroup/knowledge-flow#27]
# Config

Local knowledge-context (default):
```
knowledge_context_storage:
  type: local
  settings:
    local_path: "~/.fred/knowledge-context"
```

# Bug

If the folder doesn't already exists, it throws an error:

![Image](https://github.com/user-attachments/assets/317539cb-afae-4c48-a1dd-542a59561b8a)
